site_name: Limits' Figura Documentation
nav:
    - Home: index.md
    - Introductory Guide:
        - Mod Setup: guides/mod_setup.md
        - Your First Avatar: guides/first_avatar/p1_json.md
        - Adding a Model: guides/first_avatar/p2_model.md
        - Parent Parts: guides/first_avatar/p3_parent_parts.md
        - Scripting Intro: guides/first_avatar/p4_lua_intro.md

extra_css:
    - stylesheets/blockquotes.css

theme: readthedocs
markdown_extensions:
    - toc:
        separator: "_"
    - admonition
