site_name: Limits' Figura Documentation
nav:
    - Home: index.md
    - Introductory Guide:
        - Mod Setup: guides/mod_setup.md
        - Your First Avatar: guides/first_avatar/p1_json.md
        - Models and Parent Parts: guides/first_avatar/p2_model.md
        - Scripting Intro: guides/first_avatar/p3_lua_intro.md
    - Deprecated Pages:
        - Adding a Model: deprecated/model.md
        - Parent Parts: deprecated/parent_parts.md

extra_css:
    - stylesheets/blockquotes.css

theme: readthedocs
markdown_extensions:
    - toc:
        separator: "_"
    - admonition
